### ISSUE TITLE
Issue with the test-data faahKO_reduce.zip 

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/ipo#1]
Ping @yguitton @sneumann

I have an issue using the dataset [faahKO_reduce.zip](https://github.com/workflow4metabolomics/ipo/blob/master/galaxy/ipo/test-data/faahKO_reduce.zip) in IPO
It works when I use a sacuri sub-dataset.

I get this error message:

``` R
Error in resultIncreased(history) : 
  No isotopes have been detected, peak picking not optimizable by IPO!
Calls: ipo4xcmsSet -> optimizeXcmsSet -> resultIncreased
Execution halted
```

My parameters seem close to what I used for xcmsSet:

``` R
min_peakwidth: c(15, 25)
max_peakwidth: c(45, 55)
ppm: 25
mzdiff: c(-0.001, 0.01)
snthresh: 10
noise: 0
prefilter: 3
value_of_prefilter: 100
mzCenterFun: wMean
integrate: 1
fitgauss: FALSE
verbose.columns: FALSE
nSlaves: 1
```

Any idea?

**Comment by sneumann** [comment]
Hi, faahKO is measured on nominal mass triple quadrupole,
and not the perfect package to test IPO. Could you use 
the mtbls2 BioC package ?  Or msdata as in 
https://github.com/rietho/IPO/blob/master/inst/unitTests/test_optimizeXcmsSet.R
Yours, Steffen

**Comment by lecorguille** [comment]
Many thanks for your celerity.
I will take a look at this dataset.

**Comment by lecorguille** [comment]
Done!
2 test datasets are now used: MM14 as suggested by @sneumann and sacuri.
