### ISSUE TITLE
issue with IPO 

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/ipo#2]
Hi i have tested on galaxy dev roscoff an get a crash (history shared with lecorguille)
Fatal error: Exit code 1 ()
arguments 'minimized' and 'invisible' are for Windows only

starting new DoE with:
min_peakwidth: c(5, 15)
max_peakwidth: c(16, 65)
ppm: 0
mzdiff: c(-0.001, 0.01)
snthresh: 10
noise: 0
prefilter: 3
value_of_prefilter: 100
mzCenterFun: wMean
integrate: 1
fitgauss: FALSE
verbose.columns: FALSE
nSlaves: 1

Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: Directory tree must be level
Calls: ipo4xcmsSet ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

**Comment by lecorguille** [comment]
https://github.com/workflow4metabolomics/ipo/pull/5

**Comment by lecorguille** [comment]
Fix
