### ISSUE TITLE
IPO ppm parameter with only one value..to bad

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/ipo#3]
Hi IPO can optimize ppm setting also but for that we need to enter an interval like for peakwith.
for now we can only set X ppm as setting but not 5,15 (test from5 to 15 ppm which are best for my data set)

**Comment by lecorguille** [comment]
In the [IPO vignette](https://github.com/rietho/IPO/blob/master/vignettes/IPO.Rmd#optimize-peak-picking-parameters), I didn't read correctly:

``` r optimize_peak_picking, eval=FALSE
#setting only one value for ppm therefore this parameter is not optimized
peakpickingParameters$ppm <- 20 
```

Oups!

**Comment by lecorguille** [comment]
Thanks @yguitton 
https://github.com/workflow4metabolomics/ipo/pull/4 merged
