### ISSUE TITLE
Computation time

### ISSUE THREAD

**Issue by ethevenot** [workflow4metabolomics/ipo#6]
I have heard that computation time of the IPO software could become prohibitive when many parameters are being optimized (three or more?). I also heard that current developments were made (by the IPO developers?) to speed up the optimization by implementing genetic algorithms.

**Comment by lecorguille** [comment]
I plan to work on this aspect soon.
I guess it will be tricky to release 2 random parameters for the optimization with range of value and meanwhile let the other parameters available to be set strictly

**Comment by lecorguille** [comment]
Done
I only release one parameter at once for optimization.

**Comment by lecorguille** [comment]
If you are interesting you can have a look at the new "limited" tools into the dev instance.
